### ISSUE TITLE
Possible issue with Twig Field and Sprig (and maybe Envoyer?)

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft-twigfield#2]
### Question
I have been getting Server Errors on my staging environment since updating to the latest version of Sprig. That new version requires Twig Field, and the stack trace does mention Twig Field. So I wonder if you could have a quick look through that stacktrace (below) and see if you can see anything there (sorry, that's not one of my skills).

One thing to note is that the staging and production environments are deployed with Envoyer, so there are a few symbolic links and stuff, and the working directory is down in a "releases" directory. Could that perhaps be causing issues?

Thanks in advance for any help or advice you may be able to give!

### Additional context
Here's the stack trace:

```
yii\base\InvalidConfigException: The directory does not exist:  in /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/yiisoft/yii2/web/AssetManager.php:232
Stack trace:
#0 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/yiisoft/yii2/web/AssetManager.php(542): yii\web\AssetManager->checkBasePathPermission()
#1 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/craftcms/cms/src/web/AssetManager.php(124): yii\web\AssetManager->publishDirectory()
#2 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/yiisoft/yii2/web/AssetManager.php(474): craft\web\AssetManager->publishDirectory()
#3 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/craftcms/cms/src/web/AssetManager.php(38): yii\web\AssetManager->publish()
#4 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/craftcms/cms/src/web/AssetManager.php(52): craft\web\AssetManager->publish()
#5 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/nystudio107/craft-twigfield/src/services/AutocompleteService.php(94): craft\web\AssetManager->getPublishedUrl()
#6 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/nystudio107/craft-twigfield/src/Twigfield.php(98): nystudio107\twigfield\services\AutocompleteService::getTwigfieldPublishUrl()
#7 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/nystudio107/craft-twigfield/src/Twigfield.php(78): nystudio107\twigfield\Twigfield->configureModule()
#8 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/yiisoft/yii2/base/Application.php(295): nystudio107\twigfield\Twigfield->bootstrap()
#9 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/craftcms/cms/src/web/Application.php(122): yii\base\Application->bootstrap()
#10 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/yiisoft/yii2/base/Application.php(271): craft\web\Application->bootstrap()
#11 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/craftcms/cms/src/web/Application.php(99): yii\base\Application->init()
#12 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#13 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct()
#14 [internal function]: yii\base\Application->__construct()
#15 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#16 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#17 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#18 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/craftcms/cms/src/Craft.php(53): yii\BaseYii::createObject()
#19 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/craftcms/cms/bootstrap/bootstrap.php(239): Craft::createObject()
#20 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/vendor/craftcms/cms/bootstrap/web.php(40): require('...')
#21 /home/forge/staging.spmcommercial.co.th/releases/20220624015126/web/index.php(11): require('...')
#22 {main}
```

**Comment by khalwat** [comment]
Related: https://github.com/nystudio107/craft-seomatic/issues/1161

**Comment by khalwat** [comment]
So I think I have an idea of what might be going on here -- are you able to give something a try for me?

**Comment by khalwat** [comment]
I'm really sorry about this, we didn't catch it in local dev because it apparently rears its ugly head only right after first install/update.

Addressed in: https://github.com/nystudio107/craft-twigfield/commit/ba5a1044af3d49217f801d04316fd40626d991aa

Released as Twigfield 1.0.8: https://github.com/nystudio107/craft-twigfield/releases/tag/1.0.8

You should be able to do:

```
composer update nystudio107/craft-twigfield
```

...and it'll pull down the latest version of Twigfield (1.0.8 is the version with the fix in it). If for some reason it gets stubborn, you can do:

```
composer require nystudio107/craft-twigfield "^1.0.8"
```

**Comment by khalwat** [comment]
@AndrewMac-UTS if you can verify for me that the fix above works for you, I'd appreciate it!

**Comment by khalwat** [comment]
If you still have this issue, check to see if you see a line like this after doing `composer update nystudio107/craft-twigfield`:

```
Do you trust "yiisoft/yii2-composer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] 
```

If so, you need to update the `allow-plugins` in your `composer.json` as per:

https://github.com/craftcms/cms/issues/11500#issuecomment-1165688915

Also you should say `y` to the question it's asking, otherwise Twigfield can't be properly installed.

**Comment by ghost** [comment]
Hi @khalwat, I'm really sorry I missed your message above, but yes it's all okay now. Thanks so much for the quick work!
